name: Atualizar Propostas

on:
  schedule:
    - cron: "*/1 * * * *"  # A cada 1 minuto
  workflow_dispatch:       # Permite rodar manualmente também

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run update bot
        run: npm run update-bot
